---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: node-operator
  namespace: default
rules:
- apiGroups:
  - node.chrishein.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-operator
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: node-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-operator
subjects:
- kind: ServiceAccount
  name: node-operator
  namespace: default

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: authorizedkeys.node.chrishein.com
spec:
  group: node.chrishein.com
  names:
    kind: AuthorizedKey
    plural: authorizedkeys
    shortNames:
    - authkey
    - sshkey
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            key:
              type: string
              pattern: "#ssh-rsa AAAA[0-9A-Za-z+/]+[=]{0,3} ([^@]+@[^@]+)#"

---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: node-operator
  namespace: default
spec:
  selector:
    matchLabels:
      app: node-operator
  template:
    metadata:
      labels:
        app: node-operator
    spec:
      serviceAccountName: node-operator
      containers:
      - name: node-operator
        image: christopherhein/node-operator:0.0.9
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /authorized_keys
          name: authorized-keys
      volumes:
      - name: authorized-keys
        hostPath:
          path: /home/ec2-user/.ssh/authorized_keys
          type: File
