---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: node-operator
  namespace: default
rules:
- apiGroups:
  - authorizedKeys.node.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - authorizedkeys.nodes.io
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-operator
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: node-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-operator
subjects:
- kind: ServiceAccount
  name: node-operator
  namespace: default


---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: node-operator
  namespace: default
spec:
  selector:
    matchLabels:
      app: node-operator
  template:
    metadata:
      labels:
        app: node-operator
    spec:
      serviceAccountName: node-operator
      containers:
      - name: node-operator
        image: christopherhein/node-operator:0.0.4
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /authorized_keys
          name: authorized-keys
      volumes:
      - name: authorized-keys
        hostPath:
          path: /home/admin/.ssh/authorized_keys
          type: File
